# Case studies

---

This chapter presents case studies using sits

---

```{r, include = FALSE}
source("common.R")
```

```{r, eval = FALSE}
period <- "P16D"

output_dir <- "/data/cubes_RO_20m_P16D_cloud"

start_date <- "2020-06-01"
end_date <- "2021-09-11"

bands <- c("B02", "B03", "B04", "B05", "B08", "B8A", "B11", "B12", "CLOUD")

tile_names <- c("19LHH", "19LHJ", "20LKM", "20LKN", "20LKP", "20LLM", "20LLN",
                "20LLP", "20LLQ", "20LLR", "20LMM", "20LMN", "20LMP", "20LMQ",
                "20LMR", "20LNL", "20LNM", "20LNN", "20LNP", "20LNQ", "20LNR",
                "20LPL", "20LPM", "20LPN", "20LPP", "20LPQ", "20LQL", "20LQM",
                "20LQN", "20LRN", "20LRM", "20LRL", "20LQK", "20LPR", "20MNS",
                "20MMS", "20LKQ", "19LHK", "19LGK", "20LKR")

#### source ####

# create output directory
if (!dir.exists(output_dir))
    dir.create(output_dir)
stopifnot(dir.exists(output_dir))


s2_cube_2021 <- sits_cube(
  source = "AWS",
  collection = "SENTINEL-S2-L2A-COGS",
  bands = bands,
  tiles = tile_names,
  start_date = start_date,
  end_date = end_date,
  multicores = 20
)

# regularize
system.time({
    reg_cube <- sits_regularize(
        cube = s2_cube_2021,
        period = period,
        res = 20,
        output_dir = output_dir,
        multicores = 5,
        multithreads = 1,
        memsize = 120
    )
})

sits_apply(
    local,
    NBR = (B08 - B12) / (B08 + B12),
    memsize = 256,
    multicores = 72,
    output_dir = cube_dir
)

sits_apply(
    local,
    EVI = 2.5 * (B08 - B04) / ((B08 + 6.0 * B04 - 7.5 * B02) + 1.0),
    memsize = 256,
    multicores = 72,
    output_dir = cube_dir
)

cube_dir <- "/data/cubes_RO_20m_P16D_cloud"
out_dir <- "/data/results/RO_P16D_cloud/tcnn"
rds_samples_file <- "/data/results/RO_P16D_cloud/tcnn/samples_tb.rds"
rds_model_file <- "/data/results/RO_P16D_cloud/tcnn/model.rds"
in_samples_file <- "/home/rolf.simoes/data/samples_RO/Amostras_RO_sits_names.csv"


# --- source ----

library(dplyr)
library(sits)

if (!dir.exists(out_dir))
    dir.create(out_dir, recursive = TRUE)
stopifnot(dir.exists(out_dir))

stopifnot(file.exists(in_samples_file))

local <- sits_cube(
    source = "AWS",
    collection = "SENTINEL-S2-L2A-COGS",
    data_dir = cube_dir,
    parse_info = c("x", "tile", "band", "date"),
    multicores = 64
)

if (!file.exists(rds_samples_file)) {

    samples_tb <- sits_get_data(
        cube = local,
        file = in_samples_file,
        multicores = 10
    )

    saveRDS(samples_tb, file = rds_samples_file)
} else {
    samples_tb <- readRDS(rds_samples_file)
}

if (!file.exists(rds_model_file)) {


    model <- sits_train(
        data = samples_tb,
        ml_method = sits_lightgbm()
    )

    saveRDS(model, file = rds_model_file)
} else {
    model <- readRDS(rds_model_file)
}


probs <- sits_classify(
    data = local,
    ml_model = model,
    output_dir = out_dir,
    memsize = 400,
    multicores = 100,
    progress = TRUE
)


sits:::.sits_parallel_start(10, FALSE)

my_libpaths <- .libPaths()

parallel::clusterExport(sits:::sits_env$cluster,
                        c("probs", "out_dir", "my_libpaths"))

parallel::clusterEvalQ(sits:::sits_env$cluster,
                       .libPaths(my_libpaths))

parallel::clusterEvalQ(sits:::sits_env$cluster,
                       library(sits))

probs_bayes_lst <- sits:::.sits_parallel_map(seq_len(nrow(probs)), function(i) {

    probs_tile <- probs[i,]

    sits_smooth(
        cube = probs_tile,
        type = "bayes",
        window_size = 5,
        smoothenes = 20,
        covar = FALSE,
        multicores = 1,
        memsize = 48,
        output_dir = out_dir
    )
})

probs_bayes <- dplyr::bind_rows(probs_bayes_lst)

parallel::clusterExport(sits:::sits_env$cluster,
                        c("probs_bayes"))

class_lst <- sits:::.sits_parallel_map(seq_len(nrow(probs_bayes)), function(i) {

    probs_bayes_tile <- probs_bayes[i,]

    sits_label_classification(
        cube = probs_bayes_tile,
        multicores = 1,
        memsize = 48,
        output_dir = out_dir
    )
})

class <- dplyr::bind_rows(class_lst)


sits:::.sits_parallel_stop()

```
