# Uncertainty and active learning{-}

```{r, include = FALSE}
source("common.R")
```

The function `sits_uncertainty()` calculates the uncertainty cube based on the probabilities produced by the classifier. Takes a probability cube as input. The uncertainty measure is relevant in the context of active leaning, and helps to increase the quantity and quality of training samples by providing information about the confidence of the model. The supported types of uncertainty are 'entropy', 'least', 'margin' and 'ratio'. 'entropy' is the difference between all predictions expressed as entropy, 'least' is the difference between 100% and most confident prediction, 'margin' is the difference between the two most confident predictions, and 'ratio' is the ratio between the two most confident predictions.

cube              Probability data cube.
type              Method to measure uncertainty. See details.
window_size       Size of neighborhood to calculate entropy.
window_fn         Function to be applied in entropy calculation.
multicores        Number of cores to run the function.
memsize           Maximum overall memory (in GB) to run the
                           function
output_dir        Output directory for image files.
version           Version of resulting image.
