project:
  type: book
  output-dir: _book


book:
  title: "Satellite Image Time Series Analysis 
    on Earth Observation Data Cubes"
  reader-mode: true

  page-footer:
    background: "#21618c"
    left: |
      The SITS book was written by Gilberto Camara, Rolf Simoes, Felipe Souza, Felipe Carlos, Pedro Andrade, Karine Ferreira, Lorena Santos and Charlotte Pelletier.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  
  favicon: cover_sits_book.jpg
  site-url: https://e-sensing.github.io/sitsbook/
  repo-url: https://github.com/e-sensing/sitsbook
  repo-branch: quarto
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - setup.qmd	
    - acknowledgements.qmd
    - part: introduction.qmd
      chapters: 
        - intro_quicktour.qmd
        - intro_examples.qmd
        - intro_visualisation.qmd
    - part: datacubes.qmd
      chapters:
        - dc_ardcollections.qmd
        - dc_regularize.qmd
        - dc_merge.qmd
        - dc_localcubes.qmd
        - dc_cubeoperations.qmd
    - part: timeseries.qmd
      chapters:
        - ts_basics.qmd
        - ts_cluster.qmd
        - ts_som.qmd
        - ts_balance.qmd
    - part: classification.qmd
      chapters:
        - cl_machinelearning.qmd
        - cl_tuning.qmd
        - cl_rasterclassification.qmd
        - cl_smoothing.qmd
        - cl_reclassification.qmd
        - cl_uncertainty.qmd
        - cl_ensembleprediction.qmd
    - references.qmd
format:
  html:
    theme:
      - litera
      - sitsbook.scss
    code-link: true
    author-meta: "Gilberto Camara, Rolf Simoes, Felipe Souza, Felipe Carlos, Pedro Andrade, Karine Ferreira, Lorena Santos and Charlotte Pelletier"
    callout-appearance: simple
bibliography: e-sensing.bib
csl: ieee.csl