{
  "hash": "b1e966a308ede6e71e6235b00774dc0e",
  "result": {
    "markdown": "---\ntitle: \"Deep learning model tuning\"\nformat: html\n--- \n\n\n<a href=\"https://www.kaggle.com/code/esensing/deep-learning-model-tuning\" target=\"_blank\">\n<img src=\"https://kaggle.com/static/images/open-in-kaggle.svg\"/>\n</a>\n\n### Configurations to run this chapter{-}\n\n:::{.panel-tabset}\n## R\n\n::: {.cell}\n\n```{.r .cell-code}\n# load packages \"torch\" and \"luz\"\nlibrary(torch)\nlibrary(luz)\ntorch::install_torch()\n# load packages \"sits\" and \"sitsdata\"\nlibrary(sits)\nlibrary(sitsdata)\n# set tempdir if it does not exist \ntempdir_r <- \"~/sitsbook/tempdir/R/cl_tuning\"\ndir.create(tempdir_r, showWarnings = FALSE)\n```\n:::\n\n## Python\n\n::: {.cell}\n\n```{.python .cell-code}\n# load \"pysits\" library\nfrom pysits import *\nfrom pathlib import Path\n# set tempdir if it does not exist \ntempdir_py = Path.home() / \"sitsbook/tempdir/Python/cl_tuning\"\ntempdir_py.mkdir(parents=True, exist_ok=True)\n```\n:::\n\n::: {.cell}\n\n:::\n\n:::\n\n## Introduction\n\nModel tuning is the process of selecting the best set of hyperparameters for a specific application. When using deep learning models for image classification, it is a highly recommended step to enable a better fit of the algorithm to the training data. Hyperparameters are parameters of the model that are not learned during training but instead are set prior to training and affect the behavior of the model during training. Examples include the learning rate, batch size, number of epochs, number of hidden layers, number of neurons in each layer, activation functions, regularization parameters, and optimization algorithms.\n\nDeep learning model tuning involves selecting the best combination of hyperparameters that results in the optimal performance of the model on a given task. This is done by training and evaluating the model with different sets of hyperparameters to select the set that gives the best performance.\n\nDeep learning algorithms try to find the optimal point representing the best value of the prediction function that, given an input $X$ of data points, predicts the result $Y$. In our case, $X$ is a multidimensional time series, and $Y$ is a vector of probabilities for the possible output classes. For complex situations, the best prediction function is time-consuming to estimate. For this reason, deep learning methods rely on gradient descent methods to speed up predictions and converge faster than an exhaustive search [@Bengio2012]. All gradient descent methods use an optimization algorithm adjusted with hyperparameters such as the learning and regularization rates [@Schmidt2021]. The learning rate controls the numerical step of the gradient descent function, and the regularization rate controls model overfitting. Adjusting these values to an optimal setting requires using model tuning methods. \n\n## How SITS performs model tuning\n\nTo reduce the learning curve, `sits` provides default values for all machine learning and deep learning methods, ensuring a reasonable baseline performance. However, refining model hyperparameters might be necessary. To that end, the package provides the `sits_tuning()` function. \n\nThe most straightforward approach to model tuning is to run a grid search; this involves defining a range for each hyperparameter and then testing all possible combinations. This approach leads to a combinatorial explosion and thus is not recommended. Instead, Bergstra and Bengio propose randomly chosen trials [@Bergstra2012]. Their paper shows that randomized trials are more efficient than grid search trials, selecting adequate hyperparameters at a fraction of the computational cost. The `sits_tuning()` function follows Bergstra and Bengio by using a random search on the chosen hyperparameters.\n\nThe `sits_tuning()` function takes the following parameters:\n\n- `samples`: Training dataset to be used by the model.\n- `samples_validation`: Optional dataset containing time series to be used for validation. If missing, the next parameter will be used.\n- `validation_split`: If `samples_validation` is not used, this parameter defines the proportion of time series in the training dataset to be used for validation (default is 20%).\n- `ml_method()`: Deep learning method (either `sits_mlp()`, `sits_tempcnn()`, `sits_lstm_fcn()`, `sits_resnet()` or `sits_lighttae()`).\n- `params`: Defines the optimizer and its hyperparameters by calling  `sits_tuning_hparams()`, as shown in the example below. \n- `trials`: Number of trials to run the random search.\n- `multicores`: Number of cores to be used for the procedure.\n- `progress`: Show a progress bar?\n\nThe `sits_tuning_hparams()` function inside `sits_tuning()` allows defining optimizers and their hyperparameters, including `lr` (learning rate), `eps` (controls numerical stability), and `weight_decay` (controls overfitting). The default values for `eps` and `weight_decay` in all `sits` deep learning functions are 1e-08  and 1e-06, respectively. The default `lr` for `sits_lighttae()` and `sits_tempcnn()` is  0.005. \n\nUsers have different ways to randomize the hyperparameters, including: \n\n- `choice()` (a list of options);\n- `uniform` (a uniform distribution); \n- `randint` (random integers from a uniform distribution);\n- `normal(mean, sd)` (normal distribution);\n- `beta(shape1, shape2)` (beta distribution);\n- `loguniform(max, min)` (loguniform distribution). \n\nWe suggest to use the log-uniform distribution to search over a wide range of values that span several orders of magnitude. This is common for hyperparameters like learning rates, which can vary from very small values (e.g., 0.0001) to larger values (e.g., 1.0) in a logarithmic manner. By default, `sits_tuning()` uses a loguniform distribution between 10^-2 and 10^-4 for the learning rate and the same distribution between 10^-2 and 10^-8 for the weight decay.\n\n## Tuning a LightTAE model\n\nOur fist example is tuning a Lightweight Temporal Attention Encoder model (``sits_lightae`) [@Garnot2020] on the MOD13Q1 dataset for the state of MatoGrosso. To recall, this data set contains time series samples from the Brazilian Mato Grosso state obtained from the MODIS MOD13Q1 product. It has 1,892 samples and nine classes (`Cerrado`, `Forest`, `Pasture`, `Soy_Corn`, `Soy_Cotton`, `Soy_Fallow`, `Soy_Millet`) [@Picoli2018] and is available in the R package `sitsdata`. In this example, we show how the accuracy is related to hyperparameter `lr` (learning rate).\n\n:::{.panel-tabset}\n## R\n\n::: {.cell hash='cl_tuning_cache/html/tuning-ltae_35bbfa1c6c1edfad60716d1adfe666e3'}\n\n```{.r .cell-code}\n# Set seed \nset.seed(29031956)\n# Tuning ``sits_lighttae`` model\ntuned_mt <- sits_tuning(\n     samples = samples_matogrosso_mod13q1,\n     ml_method = sits_lighttae(),\n     params = sits_tuning_hparams(\n         optimizer = torch::optim_adamw,\n         opt_hparams = list(\n             lr = loguniform(10^-2, 10^-4)\n             )\n         ),\n     trials = 30,\n     multicores = 8,\n     seed = 29031956,\n     gpu_memory = 16,\n     batch_size = 2^16,\n     progress = FALSE\n)\ntuned_mt\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 30 × 15\n   accuracy kappa acc        samples_validation epochs batch_size\n      <dbl> <dbl> <list>     <list>              <int>      <int>\n 1    0.978 0.974 <sts_ccrc> <NULL>                150         64\n 2    0.978 0.974 <sts_ccrc> <NULL>                150         64\n 3    0.975 0.970 <sts_ccrc> <NULL>                150         64\n 4    0.973 0.967 <sts_ccrc> <NULL>                150         64\n 5    0.973 0.967 <sts_ccrc> <NULL>                150         64\n 6    0.973 0.967 <sts_ccrc> <NULL>                150         64\n 7    0.973 0.967 <sts_ccrc> <NULL>                150         64\n 8    0.973 0.967 <sts_ccrc> <NULL>                150         64\n 9    0.973 0.967 <sts_ccrc> <NULL>                150         64\n10    0.973 0.967 <sts_ccrc> <NULL>                150         64\n# ℹ 20 more rows\n# ℹ 9 more variables: validation_split <dbl>, optimizer <list>,\n#   opt_hparams <list>, lr_decay_epochs <int>, lr_decay_rate <dbl>,\n#   patience <int>, min_delta <dbl>, seed <list>, verbose <lgl>\n```\n:::\n:::\n\n## Python\n\n::: {.cell}\n\n```{.python .cell-code}\n# Set seed \nr_set_seed(29031956)\n# Load samples\nsamples_matogrosso_mod13q1 = load_samples(\n    name = \"samples_matogrosso_mod13q1\", \n    package = \"sitsdata\"\n)\n\n# Tuning ``sits_lighttae`` model\ntuned_mt = sits_tuning(\n     samples = samples_matogrosso_mod13q1,\n     ml_method = sits_lighttae,\n     params = sits_tuning_hparams(\n         optimizer = \"torch::optim_adamw\",\n         opt_hparams = dict(\n             lr = hparam(\"loguniform\", 10**-2, 10**-4),\n             weight_decay = hparam(\"loguniform\", 10**-2, 10**-8)\n             )\n         ),\n     trials = 20,\n     multicores = 8,\n     seed = 29031956,\n     gpu_memory = 16,\n     batch_size = 2^16,\n     progress = False\n)\ntuned_mt\n```\n:::\n\n::: {.cell hash='cl_tuning_cache/html/py-tuning-ltae_1de3af06dfc0658f02a1c105a274f080'}\n\n```{.r .cell-code}\ntuned_mt\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 40 × 15\n   accuracy kappa acc        samples_validation epochs    batch_size\n      <dbl> <dbl> <list>     <list>             <list>    <list>    \n 1    0.981 0.977 <sts_ccrc> <NULL>             <int [1]> <int [1]> \n 2    0.978 0.974 <sts_ccrc> <NULL>             <int [1]> <int [1]> \n 3    0.975 0.970 <sts_ccrc> <NULL>             <int [1]> <int [1]> \n 4    0.975 0.970 <sts_ccrc> <NULL>             <int [1]> <int [1]> \n 5    0.975 0.970 <sts_ccrc> <NULL>             <int [1]> <int [1]> \n 6    0.975 0.970 <sts_ccrc> <NULL>             <int [1]> <int [1]> \n 7    0.973 0.967 <sts_ccrc> <NULL>             <int [1]> <int [1]> \n 8    0.973 0.967 <sts_ccrc> <NULL>             <int [1]> <int [1]> \n 9    0.973 0.967 <sts_ccrc> <NULL>             <int [1]> <int [1]> \n10    0.970 0.964 <sts_ccrc> <NULL>             <int [1]> <int [1]> \n# ℹ 30 more rows\n# ℹ 9 more variables: validation_split <list>, optimizer <list>,\n#   opt_hparams <list>, lr_decay_epochs <list>, lr_decay_rate <list>,\n#   patience <list>, min_delta <list>, seed <list>, verbose <list>\n```\n:::\n:::\n\n:::\n\nThe result is a tibble with different values of accuracy, kappa, decision matrix, and hyperparameters. The best results obtain accuracy values between 0.978 and 0.973, as shown below. The best result is obtained by a learning rate of 0.0012. \n\n:::{.panel-tabset}\n## R\n\n::: {.cell hash='cl_tuning_cache/html/tuning-ltae-hparams_d4b134a0fec8b1a59f535d6ef3d653fc'}\n\n```{.r .cell-code}\n# Obtain accuracy, kappa, lr, and weight decay for the 5 best results\n# Hyperparameters are organized as a list\nhparams_5 <- tuned_mt[1:5,]$opt_hparams\n\n# Extract learning rate and weight decay from the list\nlr_5 <- purrr::map_dbl(hparams_5, function(h) h$lr)\n\n# Create a tibble to display the results\nbest_5 <- tibble::tibble(\n    accuracy = tuned_mt[1:5,]$accuracy,\n    kappa = tuned_mt[1:5,]$kappa,\n    lr    = lr_5)\n\n# Print the best five results\nbest_5\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 5 × 3\n  accuracy kappa       lr\n     <dbl> <dbl>    <dbl>\n1    0.978 0.974 0.00126 \n2    0.978 0.974 0.000843\n3    0.975 0.970 0.000358\n4    0.973 0.967 0.00221 \n5    0.973 0.967 0.000672\n```\n:::\n:::\n\n## Python\n\n::: {.cell}\n\n```{.python .cell-code}\n# Import pandas\nimport pandas as pd\n\n# Obtain accuracy, kappa, lr, and weight decay for the 5 best results\n# Hyperparameters are organized as a list\nhparams_5 = tuned_mt.opt_hparams[0:5]\n\n# Extract learning rate from the list\nlr_5 = [x for x_ in hparams_5 for x in x_[\"lr\"]]\n\n# Create a tibble to display the results\nbest_5 = pd.DataFrame(dict(\n    accuracy = tuned_mt.accuracy[0:5],\n    kappa = tuned_mt.kappa[0:5],\n    lr = lr_5\n))\n\n# Print the best five accuracies\nbest_5\n```\n:::\n\n::: {.cell hash='cl_tuning_cache/html/py-tuning-ltae-hparams_d0702e95b8e3834c0366e3d1717e2c49'}\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 5 × 3\n  accuracy kappa       lr\n     <dbl> <dbl>    <dbl>\n1    0.978 0.974 0.00126 \n2    0.978 0.974 0.000843\n3    0.975 0.970 0.000358\n4    0.973 0.967 0.00221 \n5    0.973 0.967 0.000672\n```\n:::\n:::\n\n:::\n\n## Tuning a TempCNN model\n\nIn the example, we use `sits_tuning()` to find good hyperparameters to train the `sits_tempcnn()` algorithm for a dataset for measuring deforestation in Rondonia (`samples_deforestation_rondonia`) available in package `sitsdata`. This dataset consists of 6,007 samples collected from Sentinel-2 images covering the state of Rondonia. There are nine classes: `Clear_Cut_Bare_Soil`, `Clear_Cut_Burned_Area`, `Mountainside_Forest`, `Forest`, `Riparian_Forest`, `Clear_Cut_Vegetation`, `Water`, `Wetland`, and `Seasonally_Flooded`. Each time series contains values from Sentinel-2/2A bands B02, B03, B04, B05, B06, B07, B8A, B08, B11 and B12, from 2022-01-05 to 2022-12-23 in 16-day intervals. The samples are intended to detect deforestation events and have been collected by remote sensing experts using visual interpretation.\n\nThe hyperparameters for the `sits_tempcnn()` method include the size of the layers, convolution kernels, dropout rates, learning rate, and weight decay. Please refer to the description of the Temporal CNN algorithm in Chapter [Machine learning for data cubes](https://e-sensing.github.io/sitsbook/machine-learning-for-data-cubes.html).\n\n:::{.panel-tabset}\n## R\n\n::: {.cell hash='cl_tuning_cache/html/tuning-tcnn_8d32d31f18d3a49cf5338bea13e25d98'}\n\n```{.r .cell-code}\n# Set seed\nset.seed(29031956)\n# Tuning ``sits_tempcnn`` model\ntuned_tempcnn <- sits_tuning(\n  samples = samples_deforestation_rondonia,\n  ml_method = sits_tempcnn(),\n  params = sits_tuning_hparams(\n    cnn_layers = choice(c(256, 256, 256), c(128, 128, 128), c(64, 64, 64)),\n    cnn_kernels = choice(c(3, 3, 3), c(5, 5, 5), c(7, 7, 7)),\n    cnn_dropout_rates = choice(c(0.2, 0.2, 0.2),\n                               c(0.3, 0.3, 0.3), \n                               c(0.4, 0.4, 0.4)),\n    optimizer = torch::optim_adamw,\n    opt_hparams = list(\n      lr = loguniform(10^-2, 10^-4),\n      weight_decay = loguniform(10^-2, 10^-8)\n    )\n  ),\n  trials = 30,\n  multicores = 8,\n  seed = 29031956,\n  gpu_memory = 16,\n  batch_size = 2^16\n)\n```\n:::\n\n## Python\n\n::: {.cell}\n\n```{.python .cell-code}\n# Set seed\nr_set_seed(29031956)\n# Load samples\nsamples_deforestation_rondonia = load_samples(\n    name = \"samples_deforestation_rondonia\", \n    package = \"sitsdata\"\n)\n\n# Tuning ``sits_tempcnn`` model\ntuned_tempcnn = sits_tuning(\n  samples = samples_deforestation_rondonia,\n  ml_method = sits_tempcnn,\n  params = sits_tuning_hparams(\n    cnn_layers = hparam(\n        \"choice\", (256, 256, 256), (128, 128, 128), (64, 64, 64)\n    ),\n    cnn_kernels = hparam(\n        \"choice\", (3, 3, 3), (5, 5, 5), (7, 7, 7)\n    ),\n    cnn_dropout_rates = hparam(\n        \"choice\", (0.2, 0.2, 0.2), (0.3, 0.3, 0.3), (0.4, 0.4, 0.4)\n    ),\n    optimizer = \"torch::optim_adamw\",\n    opt_hparams = dict(\n      lr = hparam(\"loguniform\", 10**-2, 10**-4),\n      weight_decay = hparam(\"loguniform\", 10**-2, 10**-8)\n    )\n  ),\n  trials = 20,\n  multicores = 8,\n  seed = 29031956,\n  gpu_memory = 16,\n  batch_size = 2^16\n)\n```\n:::\n\n:::\nThe result of `sits_tuning()` is  tibble with different values of accuracy, kappa, decision matrix, and hyperparameters. We list below the five best results.\n\n:::{.panel-tabset}\n## R\n\n::: {.cell hash='cl_tuning_cache/html/tuning-tcnn-hparams_912ca7dbbfced25ff2de5827922e0511'}\n\n```{.r .cell-code}\n# Obtain accuracy, kappa, cnn_layers, cnn_kernels, and cnn_dropout_rates the best result\ncnn_params <- tuned_tempcnn[1:5, c(\"accuracy\", \"kappa\", \"cnn_layers\", \"cnn_kernels\", \"cnn_dropout_rates\" )]\n\n# Get best learning rates and weight decay\nhparams_best <- tuned_tempcnn[1:5,]$opt_hparams\nlr_best <- purrr::map_dfr(hparams_best, function(h) \n  tibble::tibble(\n    lr = h$lr,\n    weight_decay = h$weight_decay)\n)\n\n# Print the best parameters \nbest_params <- dplyr::bind_cols(cnn_params, lr_best)\nbest_params\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 5 × 7\n  accuracy kappa cnn_layers   cnn_kernels cnn_dropout_rates      lr weight_decay\n     <dbl> <dbl> <chr>        <chr>       <chr>               <dbl>        <dbl>\n1    0.947 0.937 c(256, 256,… c(7, 7, 7)  c(0.2, 0.2, 0.2)  1.22e-3 0.0000000176\n2    0.946 0.936 c(128, 128,… c(3, 3, 3)  c(0.3, 0.3, 0.3)  7.18e-4 0.000000113 \n3    0.946 0.936 c(256, 256,… c(7, 7, 7)  c(0.4, 0.4, 0.4)  2.66e-3 0.000000367 \n4    0.945 0.936 c(128, 128,… c(7, 7, 7)  c(0.2, 0.2, 0.2)  2.40e-3 0.00000640  \n5    0.944 0.935 c(128, 128,… c(5, 5, 5)  c(0.4, 0.4, 0.4)  1.38e-3 0.00000211  \n```\n:::\n:::\n\n## Python\n\n::: {.cell}\n\n```{.python .cell-code}\n# Import pandas\nimport pandas as pd\n\n# Learning rates and weight decay are organized as a list\nhparams_best = tuned_tempcnn.opt_hparams[0:5]\n\n# Extract learning rate and weight decay from the list\nlr_5 = [x for x_ in hparams_best for x in x_[\"lr\"]]\nwd_5 = [x for x_ in hparams_best for x in x_[\"weight_decay\"]]\n\n# Obtain accuracy, kappa, cnn_layers, cnn_kernels, and cnn_dropout_rates the best result\npd.DataFrame(dict(\n    accuracy = tuned_tempcnn.accuracy[0:5],\n    kappa = tuned_tempcnn.kappa[0:5],\n    cnn_layers = tuned_tempcnn.cnn_layers[0:5],\n    cnn_kernels = tuned_tempcnn.cnn_kernels[0:5],\n    cnn_dropout_rates = tuned_tempcnn.cnn_dropout_rates[0:5],\n    lr = lr_5,\n    wd_best = wd_5,\n))\n```\n:::\n\n::: {.cell hash='cl_tuning_cache/html/py-tuning-tcnn-hparams_73147d97ee5a353f060e737c3f6c7fc3'}\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 4\n  accuracy kappa  lr_best wd_best\n     <dbl> <dbl>    <dbl>   <dbl>\n1    0.953 0.944 0.000695 0.00236\n```\n:::\n:::\n\n:::\n\n## Summary\n\nFor large datasets, the tuning process is time-consuming. Despite this cost, it is recommended to achieve the best performance. In general, tuning hyperparameters for models such as `sits_tempcnn()` and `sits_lighttae()` will result in a slight performance improvement over the default parameters on overall accuracy. The performance gain will be stronger in the less well represented classes, where significant gains in producer's and user's accuracies are possible. When detecting change in less frequent classes, tuning can make a relevant difference in the results.\n\n## References{-}\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}