#' Build a standalone R script that generates all book temp data
#'
#' Extracts the R code from every chapter `.qmd` and writes a single R script
#' that can be run to (re)generate the data stored under
#' `~/sitsbook/tempdir/R/<chapter>`. The script includes progress messages,
#' per-chapter timing/ETA estimates, error logging, and an optional final sync
#' of the generated R data to the Python temp directory.
#'
#' @param book_dir Path to the book project root (must contain `_quarto.yml`).
#' @param output Path for the generated R script. Defaults to
#'   `"generate_book_data.R"` in the current working directory.
#' @param chapters Optional character vector of chapter names (without `.qmd`)
#'   to limit the generation. If `NULL` (the default), all chapters are included.
#' @param skip_existing If `TRUE`, chapters whose `~/sitsbook/tempdir/R/<chapter>`
#'   directory already contains files are skipped.
#' @param python_sync If `TRUE`, the generated script calls
#'   `rsync -a ~/sitsbook/tempdir/R/ ~/sitsbook/tempdir/Python/` at the end.
#' @param chunk_times If `TRUE` (the default), the generated script times every
#'   individual code chunk, reports its line numbers in the source `.qmd`, and
#'   writes a CSV with the results. This makes it easy to identify slow chunks
#'   that should be marked `eval: false`.
#'
#' @return The path to the generated R script, invisibly.
#'
#' @export
#'
#' @examples
#' \dontrun{
#' build_data_script("/home/rolf/gh/sitsbook", "generate_book_data.R")
#' }
build_data_script <- function(book_dir,
                              output = "generate_book_data.R",
                              chapters = NULL,
                              skip_existing = TRUE,
                              python_sync = TRUE,
                              chunk_times = TRUE) {
  qmds <- chapter_files(book_dir)
  names(qmds) <- tools::file_path_sans_ext(basename(qmds))

  if (!is.null(chapters)) {
    missing <- setdiff(chapters, names(qmds))
    if (length(missing) > 0L) {
      stop("Requested chapters not found in _quarto.yml: ",
           paste(missing, collapse = ", "))
    }
    qmds <- qmds[chapters]
  }

  out_path <- normalizePath(output, winslash = "/", mustWork = FALSE)
  out_dir <- dirname(out_path)
  if (!dir.exists(out_dir)) {
    dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)
  }

  log_file <- sub("\\.R$", ".log", out_path)
  chunk_csv_file <- sub("\\.R$", "_chunks.csv", out_path)

  con <- file(out_path, "w")
  on.exit(close(con), add = TRUE)

  write_script_header(con, qmds, log_file, chunk_csv_file,
                      skip_existing, chunk_times)

  for (i in seq_along(qmds)) {
    nm <- names(qmds)[i]
    qmd <- qmds[i]
    chunks <- extract_r_chunks(qmd)
    if (chunk_times) {
      write_chapter_chunk_timed(con, nm, qmd, chunks, i, length(qmds),
                                 skip_existing)
    } else {
      code <- unlist(chunks, use.names = FALSE)
      code <- code[!grepl("install\\.packages|::install_github|::install|BiocManager::install",
                            code)]
      write_chapter_block(con, nm, qmd, code, i, length(qmds), skip_existing)
    }
  }

  write_script_footer(con, python_sync, chunk_times, chunk_csv_file)

  invisible(out_path)
}

write_script_header <- function(con, qmds, log_file, chunk_csv_file,
                                skip_existing, chunk_times) {
  skip_text <- if (skip_existing) " (skipping chapters that already have data)" else ""
  time_text <- if (chunk_times) " (per-chunk timing enabled)" else ""
  lines <- c(
    "# Generated by booksetup::build_data_script()",
    paste0("# Mode: generate book data", skip_text, time_text),
    "# Do not edit by hand.",
    "",
    "# Use a null graphics device so plot() calls do not fail in a headless run",
    "pdf(file = NULL)",
    "",
    paste0("log_file <- ", deparse(log_file)),
    "if (file.exists(log_file)) file.remove(log_file)",
    "log_con <- file(log_file, \"w\")",
    "sink(log_con, split = TRUE)",
    "sink(log_con, type = \"message\")",
    "",
    "start_global <- Sys.time()",
    "message(\"Starting book data generation at \", format(start_global))",
    "",
    sprintf("n_chapters <- %dL", length(qmds)),
    "chapter_times <- numeric(n_chapters)",
    "errors <- character()",
    if (chunk_times) {
      c(
        paste0("chunk_csv_file <- ", deparse(chunk_csv_file)),
        "chunk_log <- list()",
        ""
      )
    } else {
      ""
    },
    ""
  )
  writeLines(lines, con)
}

write_chapter_block <- function(con, chapter_name, qmd, code, i, n_chapters,
                                skip_existing) {
  skip_lines <- make_skip_lines(skip_existing)
  body <- if (length(code) > 0L) {
    paste0("    ", code)
  } else {
    "    # (no R code in this chapter)"
  }

  block <- c(
    sprintf("chapter_i <- %dL", i),
    sprintf("chapter_name <- %s", deparse(chapter_name)),
    sprintf("chapter_qmd <- %s", deparse(qmd)),
    sprintf("message(\"[%d/%d] \", chapter_name, \" -- \", format(Sys.time()))", i, n_chapters),
    skip_lines,
    "    start_chapter <- proc.time()[\"elapsed\"]",
    "    tryCatch({",
    sprintf("      # === %s ===", chapter_name),
    body,
    "    }, error = function(e) {",
    "      msg <- paste0(\"ERROR in \", chapter_name, \": \", conditionMessage(e))",
    "      message(msg)",
    "      errors <<- c(errors, msg)",
    "    })",
    "    chapter_times[chapter_i] <- proc.time()[\"elapsed\"] - start_chapter",
    "    avg <- mean(chapter_times[chapter_times > 0])",
    sprintf("    remaining <- n_chapters - %dL", i),
    "    eta <- if (is.finite(avg)) Sys.time() + remaining * avg else NA",
    "    message(\"    elapsed: \", round(chapter_times[chapter_i], 1), \"s; avg: \", round(avg, 1),",
    "            \"s; remaining: \", remaining, \"; ETA: \", format(eta))",
    "  }",
    ""
  )
  writeLines(block, con)
}

write_chapter_chunk_timed <- function(con, chapter_name, qmd, chunks, i, n_chapters,
                                      skip_existing) {
  skip_lines <- make_skip_lines(skip_existing)

  block <- c(
    sprintf("chapter_i <- %dL", i),
    sprintf("chapter_name <- %s", deparse(chapter_name)),
    sprintf("chapter_qmd <- %s", deparse(qmd)),
    sprintf("message(\"[%d/%d] \", chapter_name, \" -- \", format(Sys.time()))", i, n_chapters),
    skip_lines,
    "  {",
    sprintf("    n_chunks <- %dL", length(chunks)),
    "    chapter_elapsed <- 0"
  )

  for (j in seq_along(chunks)) {
    chunk <- chunks[[j]]
    code <- chunk
    code <- code[!grepl("install\\.packages|::install_github|::install|BiocManager::install",
                        code)]
    start_line <- attr(chunk, "start_line", exact = TRUE) %||% NA_integer_
    end_line <- attr(chunk, "end_line", exact = TRUE) %||% NA_integer_
    label <- attr(chunk, "label", exact = TRUE) %||% ""
    if (is.null(label) || !nzchar(label)) {
      label <- names(chunks)[j]
    }

    body <- if (length(code) > 0L) {
      paste0("      ", code)
    } else {
      "      # (empty or installation chunk)"
    }

    block <- c(
      block,
      sprintf("    chunk_i <- %dL", j),
      sprintf("    chunk_start_line <- %dL", start_line),
      sprintf("    chunk_end_line <- %dL", end_line),
      sprintf("    chunk_label <- %s", deparse(as.character(label))),
      sprintf("    message(\"    [chunk \", chunk_i, \"/\", n_chunks, \"] lines \", chunk_start_line, \"-\", chunk_end_line, \" (\", chunk_label, \")\")"),
      "    start_chunk <- proc.time()[\"elapsed\"]",
      "    chunk_err <- NA_character_",
      "    tryCatch({",
      sprintf("      # === %s lines %d-%d ===", chapter_name, start_line, end_line),
      body,
      "    }, error = function(e) {",
      "      chunk_err <<- conditionMessage(e)",
      "      msg <- paste0(\"ERROR in \", chapter_name, \" chunk \", chunk_i,",
      "                   \" lines \", chunk_start_line, \"-\", chunk_end_line, \":\")",
      "      message(msg)",
      "      message(chunk_err)",
      "      errors <<- c(errors, paste(msg, chunk_err))",
      "    })",
      "    chunk_elapsed <- proc.time()[\"elapsed\"] - start_chunk",
      "    chapter_elapsed <- chapter_elapsed + chunk_elapsed",
    "    message(\"      elapsed: \", round(chunk_elapsed, 1), \"s\")",
      "    chunk_log[[length(chunk_log) + 1L]] <- list(",
      "      chapter = chapter_name,",
      "      chunk = chunk_i,",
      "      start_line = chunk_start_line,",
      "      end_line = chunk_end_line,",
      "      label = chunk_label,",
      "      elapsed = chunk_elapsed,",
      "      error = chunk_err",
      "    )",
      ""
    )
  }

  block <- c(
    block,
    "    chapter_times[chapter_i] <- chapter_elapsed",
    "    avg <- mean(chapter_times[chapter_times > 0])",
    sprintf("    remaining <- n_chapters - %dL", i),
    "    eta <- if (is.finite(avg)) Sys.time() + remaining * avg else NA",
    "    message(\"    chapter elapsed: \", round(chapter_times[chapter_i], 1), \"s; avg: \", round(avg, 1),",
    "            \"s; remaining: \", remaining, \"; ETA: \", format(eta))",
    "  }",
    "}"
  )
  writeLines(block, con)
}

make_skip_lines <- function(skip_existing) {
  if (skip_existing) {
    c(
      "  chapter_data_dir <- file.path(path.expand(\"~/sitsbook/tempdir/R\"), chapter_name)",
      "  already_done <- dir.exists(chapter_data_dir) &&",
      "    length(list.files(chapter_data_dir, all.files = TRUE, recursive = TRUE)) > 0L",
      "  if (already_done) {",
      "    message(\"    skipping (data already exists)\")",
      "  } else {"
    )
  } else {
    "  {"
  }
}

write_script_footer <- function(con, python_sync, chunk_times, chunk_csv_file) {
  sync_lines <- if (python_sync) {
    c(
      "",
      "# Sync generated R data to the Python temp directory",
      "message(\"Syncing R data to Python temp directory...\")",
      "system(\"rsync -a ~/sitsbook/tempdir/R/ ~/sitsbook/tempdir/Python/\")"
    )
  } else {
    character()
  }

  chunk_summary <- if (chunk_times) {
    c(
      "",
      "# Write per-chunk timing CSV",
      "if (length(chunk_log) > 0L) {",
      "  chunk_df <- do.call(rbind, lapply(chunk_log, function(x) {",
      "    data.frame(",
      "      chapter = x$chapter,",
      "      chunk = x$chunk,",
      "      start_line = x$start_line,",
      "      end_line = x$end_line,",
      "      label = x$label,",
      "      elapsed = x$elapsed,",
      "      error = if (is.na(x$error)) \"\" else x$error,",
      "      stringsAsFactors = FALSE",
      "    )",
      "  }))",
      paste0("  write.csv(chunk_df, \"", chunk_csv_file, "\", row.names = FALSE)"),
      "  message(\"Per-chunk timing written to: ", chunk_csv_file, "\")",
      "  message(\"Top 10 slowest chunks:\")",
      "  print(head(chunk_df[order(chunk_df$elapsed, decreasing = TRUE), ], 10L))",
      "}"
    )
  } else {
    character()
  }

  footer <- c(
    "",
    sync_lines,
    chunk_summary,
    "",
    "sink(type = \"message\")",
    "sink()",
    "close(log_con)",
    "",
    "end_global <- Sys.time()",
    "message(\"Book data generation finished at \", format(end_global))",
    "message(\"Total time: \", round(difftime(end_global, start_global, units = \"mins\"), 1), \" minutes\")",
    "if (length(errors) > 0L) {",
    "  message(\"Errors encountered:\")",
    "  for (err in errors) message(err)",
    "  stop(\"Some chapters failed; see log and fix them.\", call. = FALSE)",
    "}"
  )
  writeLines(footer, con)
}
